### ISSUE TITLE
calling by reference not possible, except via std::ref?

### ISSUE THREAD

**Issue by oschonrock** [fbastos1/thread_pool_cpp17#1]
Thanks for sharing your Threadpool, which I first found on codereview. One of the cleanest and most modern I have seen. 

Having some trouble passing references to `threadpool::execute`. Your example slightly modified such that `multiply` takes one of the `int`s by reference:

```c++
int multiply(int& x, int y) {
  ++x;
  return x * y;
}

int main() {
  thread_pool                   pool;
  std::vector<std::future<int>> futures;

  std::array<int, 4> ints = {2, 4, 7, 13};
  for (int& x: ints ) {
    futures.push_back(pool.execute(multiply, x, 2));
  }

  for (auto& fut: futures) {
    std::cout << fut.get() << std::endl;
  }
  std::cout << "\n";
  for (int x: ints ) {
    std::cout << x << "\n";
  }
  return 0;
}
```
using `clang-10 -std=c++17` this throws the following:

```In file included from /home/oliver/c/chess/include/threadpool/threadpool.h:3:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/condition_variable:44:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:37:
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/tuple:1684:14: error: 
      no matching function for call to '__invoke'
      return std::__invoke(std::forward<_Fn>(__f),
             ^~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/tuple:1694:19: note: in
      instantiation of function template specialization 'std::__apply_impl<int (*)(int &,
      int), std::tuple<int, int>, 0, 1>' requested here
      return std::__apply_impl(std::forward<_Fn>(__f),
                  ^
./include/threadpool/threadpool.h:81:21: note: in instantiation of
      function template specialization 'std::apply<int (*)(int &, int), std::tuple<int,
      int> >' requested here
        return std::apply(std::move(_f), std::move(_fargs));
                    ^
main.cpp:32:28: note: in instantiation of function template
      specialization 'thread_pool::execute<int (&)(int &, int), int &, int, 0>' requested
      here
    futures.push_back(pool.execute(multiply, x, 2));
                           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:89:5: note: 
      candidate template ignored: substitution failure [with _Callable = int (*)(int &,
      int), _Args = <int, int>]: no type named 'type' in 'std::__invoke_result<int
      (*)(int &, int), int, int>'
    __invoke(_Callable&& __fn, _Args&&... __args)
    ^
1 error generated.

```
I am hitting the edge of my `&&` tolerance here trying to establish the exact cause. I think `std::make_tuple` is creating copies and those are not lvalue references anymore. 

Anyway I found a workaround, in that make_tuple will apparently retain wrappers like `std::ref`, so this works as expected:

```c++
  futures.push_back(pool.execute(multiply, std::ref(x), 2));
```
Is there a better way? I played around with `std::forward_as_tuple`, but couldn't get that through the lambda?

**Comment by oschonrock** [comment]
actually I got it to work with `std::forward_as_tuple`. Quite simply in the end. 

```diff
@@ -77,7 +77,7 @@ auto thread_pool::execute(F &&function, Args &&...args) {
       // in C++20, this could be:
       // [..., _fargs = std::forward<Args>(args)...]
       [_f = std::move(function),
-       _fargs = std::make_tuple(std::forward<Args>(args)...)]() mutable {
+       _fargs = std::forward_as_tuple(std::forward<Args>(args)...)]() mutable {
         return std::apply(std::move(_f), std::move(_fargs));
       });
   std::future<std::invoke_result_t<F, Args...>> future = task_pkg.get_future();

```

That works fine for me. Is that a legitimate fix?

**Comment by fbastos1** [comment]
I merged this without fully realizing what the problem was and, for that, I am sorry.

That's not a legitimate fix - the reason the code doesn't compile is because the loop in the example has `const int &`, and the function takes `int &`. The call is therefore illegal, and `is_invocable_v` correctly fails (albeit with a slightly more cryptic error because of the template mumbo-jumbo (I believe that's the technical term).

The correct fix would be to make sure the code is const correct - that is, either pass non-const `int`s to the function taking `int&`, or have the function take `const int&` instead.


edit: @oschonrock Thanks for the compliments! I appreciate it and I'm glad you were able to use the code I wrote here. Feel free to open another issue is you have any other problems, or to reopen this one in case it's still a problem for you. For some reason, github wasn't sending me emails for opened issues on this repo so it took me forever to notice this, but it should be all better now. Thanks for your patience!

**Comment by oschonrock** [comment]
Sorry, I don't understand why my code example above the code is not const correct. This very simiular non threaded code works:

```c++
#include <array>
#include <iostream>

int multiply(int& x, int y) {
  ++x;
  return x * y;
}

int main() {

  std::array<int, 4> ints = {2, 4, 7, 13};
  for (int x: ints ) {
    std::cout << x << "\n";
  }

  for (int& x: ints ) {
    multiply(x, 2);
  }

  std::cout << "\n";
  for (int x: ints ) {
    std::cout << x << "\n";
  }
  return 0;
}

```
Output is:

```
clang++ -Wall -Wextra const.cpp && ./a.out 
2
4
7
13

3
5
8
14

```
Just because the array uses aggregate initialisation with literal integers, does not make it const? 

Maybe I have misunderstood.
