### ISSUE TITLE
Latest update of thread_pool::execute() breaks example, and breaks my code

### ISSUE THREAD

**Issue by code-creator** [fbastos1/thread_pool_cpp17#3]
The change in latest revision in 
thread_pool::execute(F&& function, Args &&...args) {
...
from
_fargs = std::make_tuple(std::forward<Args>(args)...)]() mutable {
to
_fargs = std::forward_as_tuple(std::forward<Args>(args)...)]() mutable {
...
breaks the example from this page, which does not anymore compile.
It breaks my code too, I'm giving numbers and pointers to the exectuted function, no references and my understanding is that giving references would be a bad thing because they could dangle when the function is executed in a thread from the threadpool.

Perhaps the change in thread_pool::execute() is not the right way?

**Comment by fbastos1** [comment]
I'm looking at this again with a fresh head and I'm actually not quite sure why I merged that. The result of `std::forward` being passed as an argument to `std::forward_as_tuple` is _really_ strange. I'm going to investigate this but in the meantime, feel free to checkout HEAD^1

quick edit: I haven't looked at this code in a bit, but unless I'm missing something here the `std::forward` on that line should take care of things. I'm a bit busy right now but I'll look into this later

**Comment by fbastos1** [comment]
Update: I'm an idiot. That fix was never a fix for anything and I should've scrutinized it more before taking it at face value and merging. The problem mentioned in #1 was actually const correctness. I'm reverting to 30c52ad7 but I'll leave this issue open until I hear back from you to make sure that works for you.

**Comment by fbastos1** [comment]
9d4ac20 reverts to 4d96409

**Comment by code-creator** [comment]
Thanks fro the quick response and fix. Great class by the way!

**Comment by fbastos1** [comment]
> Thanks fro the quick response and fix. Great class by the way!

Thanks for opening the issue and for the feedback! I'm glad it was useful to you 😃
